### ISSUE TITLE
老哥  我自己写的程序提交到yarn上的时候 报错了，能不能帮忙看一下  perjob模式

### ISSUE THREAD

**Issue by rjm1990** [LinMingQiang/flink-learn#5]
2020-05-15 10:26:46,985 INFO  org.apache.flink.yarn.YarnResourceManager                     - Requesting new TaskExecutor container with resources <memory:2048, vCores:2>. Number pending requests 1.
2020-05-15 10:26:47,990 INFO  org.apache.flink.yarn.YarnResourceManager                     - Received 1 containers with 1 pending container requests.
2020-05-15 10:26:47,990 INFO  org.apache.flink.yarn.YarnResourceManager                     - Removing container request Capability[<memory:2048, vCores:2>]Priority[1]. Pending container requests 0.
2020-05-15 10:26:47,990 INFO  org.apache.flink.yarn.YarnResourceManager                     - TaskExecutor container_1589509101844_0002_01_000030 will be started on xiao101 with TaskExecutorProcessSpec {cpuCores=2.0, frameworkHeapSize=128.000mb (134217728 bytes), frameworkOffHeapSize=128.000mb (134217728 bytes), taskHeapSize=617.600mb (647600523 bytes), taskOffHeapSize=0 bytes, networkMemSize=174.720mb (183207201 bytes), managedMemorySize=698.880mb (732828804 bytes), jvmMetaspaceSize=96.000mb (100663296 bytes), jvmOverheadSize=204.800mb (214748368 bytes)}.
2020-05-15 10:26:47,990 ERROR org.apache.flink.yarn.YarnResourceManager                     - Could not start TaskManager in container container_1589509101844_0002_01_000030.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.flink.runtime.entrypoint.parser.CommandLineOptions
  at org.apache.flink.runtime.clusterframework.BootstrapTools.lambda$getDynamicPropertiesAsString$0(BootstrapTools.java:647)
  at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
  at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
  at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
  at org.apache.flink.runtime.clusterframework.BootstrapTools.getDynamicPropertiesAsString(BootstrapTools.java:653)
  at org.apache.flink.yarn.YarnResourceManager.createTaskExecutorLaunchContext(YarnResourceManager.java:578)
  at org.apache.flink.yarn.YarnResourceManager.startTaskExecutorInContainer(YarnResourceManager.java:384)
  at java.lang.Iterable.forEach(Iterable.java:75)
  at org.apache.flink.yarn.YarnResourceManager.lambda$onContainersAllocated$1(YarnResourceManager.java:366)
  at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRunAsync(AkkaRpcActor.java:397)
  at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:190)
  at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
  at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:152)
  at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
  at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
  at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
  at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
  at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
  at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
  at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
  at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
  at akka.actor.ActorCell.invoke(ActorCell.scala:561)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
  at akka.dispatch.Mailbox.run(Mailbox.scala:225)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-05-15 10:26:47,990 INFO  org.apache.flink.yarn.YarnResourceManager                     - Requesting new TaskExecutor container with resources <memory:2048, vCores:2>. Number pending requests 1.

**Comment by LinMingQiang** [comment]
缺少flink runtime的包

**Comment by Tan-JiaLiang** [comment]
老哥可以，牛批！
